version: "3.9"
services:
  springboot-app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_PORT: 3306
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.30-debian
    volumes:
      -  ecommerce-spring-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: admin

volumes:
  ecommerce-spring-db: